---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "media-capture-service.fullname" . }}
  namespace: {{ include "media-capture-service.namespace" . }}
  labels:
    {{- include "media-capture-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "media-capture-service.selectorLabels" . | nindent 4 }}
