/**
 * # Custom Script Deployment Module (Refactored)
 *
 * This module handles deployment of custom scripts to VMs using Azure VM extensions.
 * Scripts are stored in separate files for better maintainability and readability.
 */

locals {
  # Only read and encode certificate files when certificates are being generated by Terraform
  # When should_create_certificates is false, certificates are synced from Key Vault and scripts don't need them
  server_root_ca_cert         = var.should_create_certificates ? base64encode(file("${path.module}/../../../certs/server-root-ca.crt")) : ""
  server_intermediate_ca_cert = var.should_create_certificates ? base64encode(file("${path.module}/../../../certs/server-intermediate-ca.crt")) : ""
  server_leaf_ca_cert         = var.should_create_certificates ? base64encode(file("${path.module}/../../../certs/server-leaf-ca.crt")) : ""
  server_leaf_ca_key          = var.should_create_certificates ? base64encode(file("${path.module}/../../../certs/server-leaf-ca.key")) : ""

  client_root_ca_cert         = var.should_create_certificates ? base64encode(file("${path.module}/../../../certs/client-root-ca.crt")) : ""
  client_intermediate_ca_cert = var.should_create_certificates ? base64encode(file("${path.module}/../../../certs/client-intermediate-ca.crt")) : ""
  client_leaf_ca_cert         = var.should_create_certificates ? base64encode(file("${path.module}/../../../certs/client-leaf-ca.crt")) : ""
  client_leaf_ca_key          = var.should_create_certificates ? base64encode(file("${path.module}/../../../certs/client-leaf-ca.key")) : ""

  # Generate scripts using templatefile() for clean separation of concerns
  enterprise_script = templatefile("${path.module}/../../../scripts/enterprise.sh", {
    use_generated_certificates                = var.should_create_certificates
    synced_certificates_secret_name           = var.enterprise_synced_certificates_secret_name
    server_root_ca_cert                       = local.server_root_ca_cert
    server_intermediate_ca_cert               = local.server_intermediate_ca_cert
    server_leaf_ca_cert                       = local.server_leaf_ca_cert
    server_leaf_ca_key                        = local.server_leaf_ca_key
    client_root_ca_cert                       = local.client_root_ca_cert
    enterprise_broker_server_cert_secret_name = var.enterprise_broker_server_cert_secret_name
    enterprise_client_ca_configmap_name       = var.enterprise_client_ca_configmap_name
  })

  site_script = templatefile("${path.module}/../../../scripts/site.sh", {
    use_generated_certificates      = var.should_create_certificates
    synced_certificates_secret_name = var.site_synced_certificates_secret_name
    client_root_ca_cert             = local.client_root_ca_cert
    client_intermediate_ca_cert     = local.client_intermediate_ca_cert
    client_leaf_ca_cert             = local.client_leaf_ca_cert
    client_leaf_ca_key              = local.client_leaf_ca_key
    server_root_ca_cert             = local.server_root_ca_cert
    site_client_secret_name         = var.site_client_secret_name
    site_tls_ca_configmap_name      = var.site_tls_ca_configmap_name
  })
}

// Deploy enterprise script to VM via Custom Script Extension
resource "azurerm_virtual_machine_extension" "enterprise_deployment" {
  count = var.should_deploy_server_central_script ? 1 : 0

  name                        = "enterprise-script-deployment"
  virtual_machine_id          = var.server_vm_id
  publisher                   = "Microsoft.Azure.Extensions"
  type                        = "CustomScript"
  type_handler_version        = "2.1"
  automatic_upgrade_enabled   = false
  auto_upgrade_minor_version  = false
  failure_suppression_enabled = false

  protected_settings = jsonencode({
    script = base64encode(local.enterprise_script)
  })
}

// Deploy site script to VM via Custom Script Extension
resource "azurerm_virtual_machine_extension" "site_deployment" {
  count = var.should_deploy_client_technology_script ? 1 : 0

  name                        = "site-script-deployment"
  virtual_machine_id          = var.client_vm_id
  publisher                   = "Microsoft.Azure.Extensions"
  type                        = "CustomScript"
  type_handler_version        = "2.1"
  automatic_upgrade_enabled   = false
  auto_upgrade_minor_version  = false
  failure_suppression_enabled = false

  protected_settings = jsonencode({
    script = base64encode(local.site_script)
  })
}
