---
# Azure DevOps to GitHub Push Pipeline
#
# Purpose:
# This pipeline synchronizes code from Azure DevOps to GitHub repositories, creating
# pull requests for changes and managing version tagging based on GitVersion. It ensures
# the internal Azure DevOps repository changes are reflected in the public GitHub repository.
#
# When to use:
# - Automatically triggered when main or pre-release branches are updated in Azure DevOps
# - When you need to publish internal changes to the public GitHub repository
# - After merging PRs in Azure DevOps that should be reflected in GitHub
# - When implementing bidirectional sync between Azure DevOps and GitHub
#
# Functionality:
# - Authenticates with GitHub using GitHub App installation tokens
# - Pushes changes from Azure DevOps branch to corresponding GitHub branch
# - Creates pull requests in GitHub for review and integration
# - Calculates semantic versions using GitVersion (main branch only)
# - Creates and pushes Git tags based on calculated versions
# - Supports both main and pre-release branch workflows
#
# Prerequisites:
# - Variable group 'ai-on-edge-secrets' with GitHub App credentials:
#   - github-edge-ai-app-client-id: GitHub App client ID
#   - github-edge-ai-app-private-key: GitHub App private key (PEM format)
#   - github-edge-ai-repo-url: GitHub repository URL with __token__ placeholder
# - Managed agent pool: ai-on-edge-managed-pool
# - GitVersion configuration file (GitVersion.yml) in repository root
# - System.AccessToken for Azure DevOps git operations
#
# Parameters:
# None - Pipeline behavior controlled by branch triggers (isMain, isPreRelease variables)
#
# Output Variables:
# - githubAuth.installationToken: GitHub installation token (from github-auth.yml)
# - gitPush.pushedBranchName: Name of branch pushed to GitHub
# - githubPR.number: Pull request number created in GitHub
# - githubPR.url: URL of created pull request
# - GitVersion.MajorMinorPatch: Calculated semantic version (main branch only)
#
# Template Dependencies:
# - ../templates/github-auth.yml: GitHub App authentication
# - ../templates/git-sync-operations.yml: Git push operations (requires workingDirectory, targetBranch)
# - ../templates/pr-creation.yml: GitHub PR creation (uses installationToken, repository, head, base)
#
# Notes:
# - Pipeline only runs for main and pre-release branches (condition check)
# - git-sync-operations.yml requires workingDirectory and targetBranch parameters
# - pr-creation.yml requires installationToken (not githubToken)
# - PR creation uses head, base, repository parameters (not headBranch, baseBranch, repositoryName)
# - GitVersion task runs only on main branch (dependsOn: GitHubPush)
# - Git tag push uses System.AccessToken for Azure DevOps authentication

# GitHub sync pipeline
---
trigger: none
variables:
  - group: 'ai-on-edge-secrets'
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isPreRelease
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/pre-release')]
pool:
  name: ai-on-edge-managed-pool
  vmImage: ubuntu-latest
stages:
  - stage: Main
    displayName: AzDO to GitHub
    jobs:
      - job: "GitHubPush"
        displayName: "Updating GitHub repo from AzDO"
        condition: or(eq(variables.isMain, true), eq(variables.isPreRelease, true))
        steps:
          # Checkout repo
          - checkout: self
            fetchDepth: "0"
            clean: true

          # GitHub App Authentication
          - template: ../templates/github-auth.yml
            parameters:
              githubRepository: 'microsoft/edge-ai'
              outputVariableName: 'installationToken'
              displayName: 'Create GitHub access token'

          # Push to GitHub using standardized template
          - template: ../templates/git-sync-operations.yml
            parameters:
              operation: 'push-to-github'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              sourceBranch: '$(Build.SourceBranch)'
              targetBranch: '$(Build.SourceBranchName)'
              createNewBranch: true
              forceWithLease: false

          # Create GitHub PR using template
          - template: ../templates/pr-creation.yml
            parameters:
              operation: 'create-pr'
              installationToken: '$(githubAuth.installationToken)'
              repository: 'microsoft/edge-ai'
              head: '$(gitPush.pushedBranchName)'
              base: '$(Build.SourceBranch)'
              title: 'AzDO sync for branch $(gitPush.pushedBranchName)'
              body: '$(Build.SourceVersionMessage)'
              draft: false
              maintainerCanModify: true
            displayName: "Create GitHub PR"
            name: githubPR

      - job: "Versioning"
        displayName: "Updating Version based on Git Tag"
        dependsOn: GitHubPush
        condition: and(succeeded(), eq(variables.isMain, true))
        steps:
          # Checkout repo
          - checkout: self
            fetchDepth: "0"
            clean: true

          # Install GitVersion
          - task: gitversion/setup@3
            name: installGitVersion
            displayName: Install GitVersion
            inputs:
              versionSpec: '5.x'

          # Determine Version
          - task: gitversion/execute@3
            name: executeGitVersion
            displayName: Determine Version
            inputs:
              useConfigFile: true
              configFilePath: ./GitVersion.yml

          # Create Git Tag
          - pwsh: |
              git tag "$(GitVersion_MajorMinorPatch)"
            displayName: Create git tag
            name: createGitTag

          # Push Git Tag
          - pwsh: |
              $accessToken = "$(System.AccessToken)"
              git -c http.extraheader="AUTHORIZATION: bearer $accessToken" push origin "$(GitVersion_MajorMinorPatch)"
            displayName: Push git tag
            name: pushGitTag
