# yamllint configuration file
# Extracted from .mega-linter.yml for standalone use
---
extends: default

rules:
  # Line length rule - disabled to allow long lines in Azure DevOps pipelines
  line-length: disable
  # Original configuration (commented out):
  # line-length:
  #   max: 120
  #   allow-non-breakable-words: true
  #   allow-non-breakable-inline-mappings: true
  #   level: warning

  # Comments rule - allow comments at the beginning of the line
  comments:
    min-spaces-from-content: 1

  # Indentation rule - 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Trailing spaces rule
  trailing-spaces: enable

  # Empty lines rule
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Document start rule - encourage document start markers (soft warning)
  # This ensures all YAML files (including front matter) are properly formatted
  document-start:
    present: true
    level: warning

  # Truthy rule - allow 'on' for GitHub/Azure DevOps triggers
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
    check-keys: true

  # New lines rule - disabled
  new-lines: disable

  # Key duplicates rule
  key-duplicates: enable

  # Brackets rule
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces rule
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

# Ignore patterns from MegaLinter configuration
ignore: |
  .github/ISSUE_TEMPLATE/*
  charts/templates/*
  charts/*/templates/*
  **/node_modules/**
  docs/assets/js/node_modules/**
  docs/_server/node_modules/**
  **/charts/**/templates/*
  src/**/charts/**/templates/*
