apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros2-connector.fullname" . }}
  labels:
    {{- include "ros2-connector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ros2-connector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ros2-connector.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ros2-connector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: {{ .Values.networkPolicy.useHostNetwork }}
      dnsPolicy: {{ .Values.networkPolicy.dnsPolicy }}
      containers:
        - name: connector
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: ROS_LOG_DIR
              value: /tmp
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- if and .Values.cycloneDDS.enabled (not .Values.customCycloneDDSUri) }}
            - name: CYCLONEDDS_URI
              value: "file:///app/cyclone-dds.xml"
            {{- else if .Values.customCycloneDDSUri }}
            - name: CYCLONEDDS_URI
              value: {{ .Values.customCycloneDDSUri | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          {{- if or .Values.cycloneDDS.enabled .Values.configMap.enabled .Values.volumeMounts }}
          volumeMounts:
            {{- if .Values.cycloneDDS.enabled }}
            - name: cyclone-dds-config
              mountPath: /app/cyclone-dds.xml
              subPath: cyclone-dds.xml
              readOnly: true
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if or .Values.cycloneDDS.enabled }}
      volumes:
        {{- if .Values.cycloneDDS.enabled }}
        - name: cyclone-dds-config
          configMap:
            name: {{ include "ros2-connector.fullname" . }}-cyclonedds
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
