---
apiVersion: "arccontainerstorage.azure.net/v1"
kind: EdgeSubvolume
metadata:
  name: {SUBVOLUME_NAME}
spec:
  edgevolume: {EDGE_VOLUME_NAME}
  path: {PATH}
  auth:
    authType: MANAGED_IDENTITY
  storageaccountendpoint: "https://{STORAGE_ACCOUNT_NAME}.blob.core.windows.net/"
  container: {CONTAINER_NAME}
  ingestPolicy: edgeingestpolicy-default # Optional: See the following instructions if you want to update the ingestPolicy with your own configuration
