# GitHub Push Template
#
# Purpose:
# This template defines a job for pushing content from GitHub repositories into the Azure DevOps
# repository. It's used to push private repository changes to public and ensure internal
# and external versions of this project stay in sync.
#
# When to use:
# - When you need to publish build artifacts to GitHub
# - When synchronizing documentation or generated code to GitHub repositories
# - When contributing automated changes back to upstream repositories
# - When implementing a mirroring strategy between Azure DevOps and GitHub
#
# Functionality:
# - Configures Git with appropriate credentials and settings
# - Pushes content from the pipeline workspace to specified GitHub repositories
# - Supports different authentication methods for GitHub access
# - Can target specific branches or create new branches as needed
#
# Parameters:
# - isEnterpriseGitHub: Boolean to determine if the GitHub repository is internal or public
#
# Key Parameters:
# - targetRepo: The GitHub repository URL to push to
# - sourcePath: The local path containing content to be pushed
# - targetBranch: Which branch to push changes to
# - commitMessage: The message to use for the commit
# - auth: Authentication details for GitHub access

# GitHub sync pipeline
---
trigger: none
variables:
  - group: 'ai-on-edge-secrets'
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
pool:
  name: ai-on-edge-managed-pool
  vmImage: ubuntu-latest
stages:
  - stage: Main
    displayName: AzDO to GitHub
    jobs:
      - job: "GitHubPush"
        displayName: "Updating GitHub repo from AzDO"
        # condition: eq(variables.isMain, true)
        steps:
          # Checkout repo
          - checkout: self
            fetchDepth: "0"
            clean: true

          # Create GitHub access token
          - bash: |
              githubAppClientId=$(echo $(github-edge-ai-app-client-id))
              echo "$(github-edge-ai-app-private-key)" > ./github-app-private-key.pem

              echo "Generating Github JWT Token"
              token=$(bash $(System.DefaultWorkingDirectory)/scripts/github/jwt-token.sh $githubAppClientId ./github-app-private-key.pem)

              echo "Generating Github Access Tokens Url"
              repo_path=$(echo $(github-edge-ai-repo-url) | sed -n 's|.*github.com/\([^/][^/]*/[^/][^/]*\)/$|\1|p')
              echo "Repo Path: $repo_path"
              url=$(bash $(System.DefaultWorkingDirectory)/scripts/github/access-tokens-url.sh $token $repo_path)

              echo "Generating Github Installation Token"
              installationToken=$(bash $(System.DefaultWorkingDirectory)/scripts/github/installation-token.sh $token $url)
              echo "##vso[task.setvariable variable=installationToken]$installationToken";

            displayName: "Create GitHub access token"
            name: githubToken

          # Push to GitHub
          - bash: |
              githubUrl=$(github-edge-ai-repo-url)

              echo "Pushing to GitHub"
              remoteUrl=$(echo $githubUrl | sed "s|__token__|$(installationToken)|g")
              echo "Remote URL: $remoteUrl"
              git remote remove origin
              git remote add origin $remoteUrl
              echo "Switching to a new temporary branch to leave the detached mode"
              git switch -c azdo-$(Build.BuildId)
              echo "$(git branch --all)"
              git push --force origin azdo-$(Build.BuildId):azdo-$(Build.BuildId)
              git remote remove origin
              echo "Pushed branch azdo-$(Build.BuildId) to GitHub"

            displayName: "Push to GitHub"
            name: githubPush

          # Create GitHub PR
          - bash: |

              echo "Creating PR"
              repo_path=$(echo $(github-edge-ai-repo-url) | sed -n 's|.*github.com/\([^/][^/]*/[^/][^/]*\)/$|\1|p')
              bash $(System.DefaultWorkingDirectory)/scripts/github/create-pr.sh "$(installationToken)" "azdo-$(Build.BuildId)" "$(Build.SourceVersionMessage)" "$repo_path"

            displayName: "Create GitHub PR"
            name: githubPR

      - job: "Versioning"
        displayName: "Updating Version based on Git Tag"
        dependsOn: GitHubPush
        condition: and(succeeded(), eq(variables.isMain, true))
        steps:
          # Checkout repo
          - checkout: self
            fetchDepth: "0"
            clean: true

          # Install GitVersion
          - task: gitversion/setup@3
            name: installGitVersion
            displayName: Install GitVersion
            inputs:
              versionSpec: '5.x'

          # Determine Version
          - task: gitversion/execute@3
            name: executeGitVersion
            displayName: Determine Version
            inputs:
              useConfigFile: true
              configFilePath: ./GitVersion.yml

          # Create Git Tag
          - bash: |
              git tag $(GitVersion_MajorMinorPatch)
            displayName: Create git tag
            name: createGitTag

          # Push Git Tag
          - bash: |
              git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin $(GitVersion_MajorMinorPatch)
            displayName: Push git tag
            name: pushGitTag
