---
# NVIDIA GPU Operator Helm values override for Azure ML
# This file contains minimal overrides for Azure ML GPU workloads

# Disable driver installation (managed by Azure ML)
driver:
  # enabled: true
  enabled: false

# Disable toolkit (managed by Azure ML)
toolkit:
  enabled: true

# Enable Node Feature Discovery
nfd:
  enabled: true

# Enable CRD upgrades and add Azure spot instance tolerations to operator
operator:
  upgradeCRD: true

# Disable MIG Manager
migManager:
  enabled: false

# Add Azure spot instance tolerations to all daemonsets
daemonsets:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
    - key: kubernetes.azure.com/scalesetpriority
      operator: Equal
      value: spot
      effect: NoSchedule

# Add Azure spot instance tolerations to Node Feature Discovery
node-feature-discovery:
  worker:
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      - key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
        effect: NoSchedule
