---
apiVersion: v1
data:
  prometheus-config: |2-
    # Global configuration for Prometheus scraping
    global:
      scrape_interval: 1m
      evaluation_interval: 1m
      scrape_timeout: 10s

    scrape_configs:
      # Scrape the OpenTelemetry collector metrics endpoint
      - job_name: otel-collector
        scrape_interval: 1m
        metrics_path: /metrics
        static_configs:
          - targets:
            - aio-otel-collector.azure-iot-operations.svc.cluster.local:8889
        metric_relabel_configs:
          # Add a cluster label to all metrics
          - source_labels: []
            target_label: cluster
            replacement: 'edge-cluster'

      # Scrape Kubernetes pods with Prometheus annotations
      - job_name: aio-annotated-pod-metrics
        scrape_interval: 1m
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Skip init containers
          - action: drop
            regex: true
            source_labels:
              - __meta_kubernetes_pod_container_init
          # Only scrape pods with the scrape annotation
          - action: keep
            regex: true
            source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
          # Set metrics path if specified
          - action: replace
            regex: (.+)
            source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            target_label: __metrics_path__
          # Replace address with annotated port
          - action: replace
            regex: ([^:]+)(?::\\d+)?;(\\d+)
            replacement: $1:$2
            source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
            target_label: __address__
          # Set pod namespace as a label
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: kubernetes_namespace
          # Set pod name as a label
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: kubernetes_pod_name
          # Only include pods from the IoT Operations namespace
          - action: keep
            regex: 'azure-iot-operations'
            source_labels:
              - kubernetes_namespace

      # Scrape Node metrics (kubelet)
      - job_name: kubernetes-nodes
        scrape_interval: 1m
        scheme: https
        tls_config:
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics
kind: ConfigMap
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system
