---
# Updated OpenTelemetry Collector configuration for Azure IoT Operations
# Uses recommended best practices for a production deployment

mode: deployment
fullnameOverride: aio-otel-collector

# Using the contrib image which includes additional components
image:
  repository: otel/opentelemetry-collector
  tag: 0.126.0 # Updated to a specific version for stability
  pullPolicy: IfNotPresent # Added explicit pull policy

config:
  processors:
    memory_limiter:
      limit_percentage: 80
      spike_limit_percentage: 10
      check_interval: '60s'
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
    otlp:
      protocols:
        grpc:
          endpoint: ':4317'
        http:
          endpoint: ':4318'
  exporters:
    prometheus:
      endpoint: ':8889'
      resource_to_telemetry_conversion:
        enabled: true
      add_metric_suffixes: false
  service:
    extensions:
      - health_check
    pipelines:
      metrics:
        receivers:
          - otlp
        exporters:
          - prometheus
      logs: null
      traces: null
    telemetry:
      metrics:
        readers:
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133
resources:
  limits:
    cpu: '100m'
    memory: '512Mi'
ports:
  metrics:
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: 'TCP'
  jaeger-compact:
    enabled: false
  jaeger-grpc:
    enabled: false
  jaeger-thrift:
    enabled: false
  zipkin:
    enabled: false
