apiVersion: azmonitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nvidia-dcgm-exporter
  namespace: kube-system
  labels:
    app: nvidia-dcgm-exporter
spec:
  namespaceSelector:
    matchNames:
      - gpu-operator
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
