{{- if and .Values.models.createClaim (not .Values.models.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai-edge-inference.modelClaimName" . }}
  namespace: {{ include "ai-edge-inference.namespace" . }}
  labels:
    {{- include "ai-edge-inference.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.models.accessModes | nindent 4 }}
  {{- with .Values.models.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.models.size }}
{{- end }}