{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-edge-inference.serviceAccountName" . }}
  namespace: {{ include "ai-edge-inference.namespace" . }}
  labels:
    {{- include "ai-edge-inference.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}