apiVersion: fabric.ontology/v1
kind: OntologyDefinition

metadata:
  name: "CORA_CORAX_Dimensional"
  description: "IEEE 1872 CORA/CORAX Robotics Ontology - Dimensional Schema"
  version: "1.0.0"

dataSources:
  lakehouse:
    name: "RoboticsOntologyLH"
    tables:
      # 12 Entity tables (lowercase names for Lakehouse)
      - name: "robot"
        format: "csv"
      - name: "robotgroup"
        format: "csv"
      - name: "roboticsystem"
        format: "csv"
      - name: "roboticenvironment"
        format: "csv"
      - name: "robotinterface"
        format: "csv"
      - name: "processingdevice"
        format: "csv"
      - name: "physicalenvironment"
        format: "csv"
      - name: "positioncoordinatesystem"
        format: "csv"
      - name: "orientationcoordinatesystem"
        format: "csv"
      - name: "positionmeasure"
        format: "csv"
      - name: "orientationmeasure"
        format: "csv"
      - name: "posemeasure"
        format: "csv"
      # 7 Relationship tables
      - name: "robot_robotgroup"
        format: "csv"
      - name: "robot_roboticsystem"
        format: "csv"
      - name: "roboticenvironment_roboticsystem"
        format: "csv"
      - name: "coordinatesystem_transformations"
        format: "csv"
      - name: "robot_positionmeasure"
        format: "csv"
      - name: "robot_orientationmeasure"
        format: "csv"
      - name: "robot_posemeasure"
        format: "csv"

entityTypes:
  # --- CORA Entities ---
  - name: "Robot"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "robot"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

  - name: "RobotGroup"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "robotgroup"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

  - name: "RoboticSystem"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "roboticsystem"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

  - name: "RoboticEnvironment"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "roboticenvironment"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

  - name: "RobotInterface"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "robotinterface"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

  # --- CORAX Entities ---
  - name: "ProcessingDevice"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "processingdevice"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

  - name: "PhysicalEnvironment"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "physicalenvironment"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

  # --- POS Entities ---
  - name: "PositionCoordinateSystem"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "positioncoordinatesystem"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

  - name: "OrientationCoordinateSystem"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "orientationcoordinatesystem"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

  - name: "PositionMeasure"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "positionmeasure"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "X"
        type: "double"
        sourceColumn: "X"
      - name: "Y"
        type: "double"
        sourceColumn: "Y"
      - name: "Z"
        type: "double"
        sourceColumn: "Z"
      - name: "CoordinateSystemId"
        type: "string"
        sourceColumn: "CoordinateSystemId"
      - name: "Timestamp"
        type: "string"
        sourceColumn: "Timestamp"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

  - name: "OrientationMeasure"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "orientationmeasure"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "Roll"
        type: "double"
        sourceColumn: "Roll"
      - name: "Pitch"
        type: "double"
        sourceColumn: "Pitch"
      - name: "Yaw"
        type: "double"
        sourceColumn: "Yaw"
      - name: "CoordinateSystemId"
        type: "string"
        sourceColumn: "CoordinateSystemId"
      - name: "Timestamp"
        type: "string"
        sourceColumn: "Timestamp"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

  - name: "PoseMeasure"
    key: "Id"
    displayName: "Name"
    dataBinding:
      type: "static"
      source: "lakehouse"
      table: "posemeasure"
    properties:
      - name: "Id"
        type: "string"
        sourceColumn: "Id"
      - name: "Name"
        type: "string"
        sourceColumn: "Name"
      - name: "Description"
        type: "string"
        sourceColumn: "Description"
      - name: "X"
        type: "double"
        sourceColumn: "X"
      - name: "Y"
        type: "double"
        sourceColumn: "Y"
      - name: "Z"
        type: "double"
        sourceColumn: "Z"
      - name: "Roll"
        type: "double"
        sourceColumn: "Roll"
      - name: "Pitch"
        type: "double"
        sourceColumn: "Pitch"
      - name: "Yaw"
        type: "double"
        sourceColumn: "Yaw"
      - name: "CoordinateSystemId"
        type: "string"
        sourceColumn: "CoordinateSystemId"
      - name: "Timestamp"
        type: "string"
        sourceColumn: "Timestamp"
      - name: "Namespace"
        type: "string"
        sourceColumn: "Namespace"
      - name: "Source"
        type: "string"
        sourceColumn: "Source"

relationships:
  - name: "member"
    description: "Robot is member of RobotGroup"
    from: "Robot"
    to: "RobotGroup"
    cardinality: "many-to-many"
    binding:
      table: "robot_robotgroup"
      fromColumn: "FromId"
      toColumn: "ToId"

  - name: "partOf"
    description: "Robot is part of RoboticSystem"
    from: "Robot"
    to: "RoboticSystem"
    cardinality: "many-to-many"
    binding:
      table: "robot_roboticsystem"
      fromColumn: "FromId"
      toColumn: "ToId"

  - name: "equippedWith"
    description: "RoboticEnvironment is equipped with RoboticSystem"
    from: "RoboticEnvironment"
    to: "RoboticSystem"
    cardinality: "many-to-many"
    binding:
      table: "roboticenvironment_roboticsystem"
      fromColumn: "FromId"
      toColumn: "ToId"

  - name: "transform"
    description: "PositionCoordinateSystem transforms to OrientationCoordinateSystem"
    from: "PositionCoordinateSystem"
    to: "OrientationCoordinateSystem"
    cardinality: "many-to-many"
    binding:
      table: "coordinatesystem_transformations"
      fromColumn: "FromId"
      toColumn: "ToId"

  - name: "hasPosition"
    description: "Robot has PositionMeasure"
    from: "Robot"
    to: "PositionMeasure"
    cardinality: "many-to-many"
    binding:
      table: "robot_positionmeasure"
      fromColumn: "FromId"
      toColumn: "ToId"

  - name: "hasOrientation"
    description: "Robot has OrientationMeasure"
    from: "Robot"
    to: "OrientationMeasure"
    cardinality: "many-to-many"
    binding:
      table: "robot_orientationmeasure"
      fromColumn: "FromId"
      toColumn: "ToId"

  - name: "hasPose"
    description: "Robot has PoseMeasure"
    from: "Robot"
    to: "PoseMeasure"
    cardinality: "many-to-many"
    binding:
      table: "robot_posemeasure"
      fromColumn: "FromId"
      toColumn: "ToId"
