# Hadolint configuration for ROS2 connector application
#
# Mirrors root .hadolint.yaml settings.
# Hadolint does not merge configs; this file fully replaces root.
# Hadolint discovers config from CWD ($PWD), not from the Dockerfile
# location. Use --config to load this file when running from repo root.
#
# Architecture: MCR Ubuntu base images (SHA256-pinned) with ROS2 Jazzy
# installed via apt packages. No DL3006 exemption needed.
---
failure-threshold: warning

ignored:
  - SC1091

trustedRegistries:
  - mcr.microsoft.com
  - docker.io
