{
 "title": "Latency",
 "tags": [ "latency" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "pds", "label": "prometheus data source", "query": "prometheus" },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "appinsight",
    "label": "AppInsight",
    "query": {}
   },
   {
    "name": "aiuri",
    "query": "/subscriptions/$sub/resourceGroups/$rg/providers/microsoft.insights/components/$appinsight"
   },
   {
    "name": "lgws",
    "label": "Log Analytics workspace",
    "query": {}
   },
   {
    "name": "storage",
    "label": "Storage Account",
    "query": {}
   },
   {
    "name": "device",
    "label": "Device Name",
    "query": {}
   },
   { "name": "cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "LogPodNameSpace",
    "label": "Pod Namespace",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Light Edge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Device Latency",
   "type": "bargauge",
   "description": "Device latency",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AppDependencies\n| summarize avgDuration=avg(DurationMs) by AppRoleName\n| project AppRoleName, avgDuration",
      "resources": [ "$lgws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "$device Average Device Latency",
   "type": "timeseries",
   "description": "Device latency overtime",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "repeat": "device",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AppDependencies\n| where AppRoleName==$device\n| summarize avgDuration=avg(DurationMs) by AppRoleName, TimeGenerated\n| project AppRoleName, avgDuration, TimeGenerated\n| order by TimeGenerated asc ",
      "resources": [ "$lgws" ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  { "title": "Medium Edge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "All Timeouts in $cluster - $LogPodNameSpace namespace ",
   "type": "piechart",
   "description": "Total time outs recorded in this namespace",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "ContainerLogV2\n| where _ResourceId contains \"${cluster}\"\n| where PodNamespace==(\"$LogPodNameSpace\") and LogMessage contains \"Timed Out\"\n| extend Image=tostring(KubernetesMetadata[\"image\"])\n| summarize Timeouts=count() by Image",
      "resources": [ "$lgws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Container timeouts $cluster - $LogPodNameSpace (${__from:date:YYYY-MM-DD} - ${__to:date:YYYY-MM-DD})",
   "type": "piechart",
   "description": "Total Container Timeout for the time range of dashboard  \n       ${__from:date:YYYY-MM-DD} -\n       ${__to:date:YYYY-MM-DD}",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "ContainerLogV2\n| where _ResourceId contains \"${cluster}\" and PodNamespace==(\"$LogPodNameSpace\") and LogMessage contains \"Timed Out\"\n| summarize Timeouts=count() by ContainerName",
      "resources": [ "$lgws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Image timeouts in $LogPodNameSpace (${__from:date:YYYY-MM-DD} - ${__to:date:YYYY-MM-DD})",
   "type": "table",
   "description": "Timeouts observed in each namespace. Seperated by k8s Image reporting the error. ",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 22 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "ContainerLogV2\n| where PodNamespace==(\"$LogPodNameSpace\") and LogMessage contains \"Timed Out\"\n| extend Image=tostring(KubernetesMetadata[\"image\"])\n| summarize Timeouts=count() by Image\n| order by Timeouts desc ",
      "resources": [ "$lgws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Image timeouts from the last 7days in $LogPodNameSpace namespace",
   "type": "piechart",
   "description": "Image time outs over the last 7 day span. ",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "ContainerLogV2\n| where _ResourceId contains \"${cluster}\"\n| where PodNamespace==(\"$LogPodNameSpace\") and LogMessage contains \"Timed Out\" and TimeGenerated > ago(7d)\n| extend Image=tostring(KubernetesMetadata[\"image\"])\n| summarize Timeouts=count() by bin(TimeGenerated, 7d), Image",
      "resources": [ "$lgws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Pod timeouts in $LogPodNameSpace (${__from:date:YYYY-MM-DD} - ${__to:date:YYYY-MM-DD})",
   "type": "table",
   "description": "Timeouts observed in each namespace. Seperated by k8s Pods reporting the error. ",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "ContainerLogV2\n| where _ResourceId contains \"${cluster}\"\n| where PodNamespace==(\"$LogPodNameSpace\") and LogMessage contains \"Timed Out\"\n| summarize Timeouts=count() by PodName\n| order by Timeouts desc ",
      "resources": [ "$lgws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Service Failures in the last 7 days",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 31 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AppDependencies\n| where ResultCode == 2 and Success == false and TimeGenerated > ago(7d)\n| extend ServiceName=tostring(Properties[\"service.name\"])\n| summarize count() by bin(TimeGenerated,1d), ServiceName\n| order by TimeGenerated asc",
      "resources": [ "$lgws" ],
      "resultFormat": "table",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Timeout totals per image in $cluster (${__from:date:YYYY-MM-DD} - ${__to:date:YYYY-MM-DD})",
   "type": "table",
   "description": "Image timeouts across cluster in within the provided window, all values from the above tables should be represented here. ",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 32 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "ContainerLogV2\n| where _ResourceId contains \"${cluster}\" and LogMessage contains \"Timed Out\"\n| extend Image=tostring(KubernetesMetadata[\"image\"])\n| summarize Timeouts=count() by Image, ContainerName\n| order by Timeouts desc \n",
      "resources": [ "$lgws" ],
      "resultFormat": "table",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Container Timeouts in $cluster (24h)",
   "type": "piechart",
   "description": "Timeouts by Container for the past 24hrs.",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "ContainerLogV2\n| where _ResourceId contains \"${cluster}\" and LogMessage contains \"Timed Out\" and TimeGenerated > ago(24h)\n| summarize Timeouts=count() by ContainerName",
      "resources": [ "$lgws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "$cluster MQTT Broker average latency",
   "type": "bargauge",
   "description": "Broker latency across all its actions. \nConnection, Publish, Subscribe, Unsubscribe",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace((avg by (cluster)(aio_broker_connect_latency_route_ms{cluster=~\"$cluster\"})), \"custom_label\", \"connect\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    },
    {
     "expr": "label_replace((avg by (cluster)(aio_broker_publish_latency_route_ms{cluster=~\"$cluster\"})), \"custom_label\", \"publish\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    },
    {
     "expr": "label_replace((avg by (cluster)(aio_broker_message_delivery_check_latency_last_value_ms{cluster=\"$cluster\"})),\"custom_label\", \"message delivery\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    },
    {
     "expr": "label_replace((avg by (cluster)(aio_broker_subscribe_latency_route_ms{cluster=~\"$cluster\"})), \"custom_label\", \"subscribe\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    },
    {
     "expr": "label_replace((avg by (cluster)(aio_broker_unsubscribe_latency_route_ms{cluster=~\"$cluster\"})), \"custom_label\", \"unsubscribe\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    },
    {
     "expr": "label_replace((avg by (cluster) (aio_broker_ping_latency_route_ms{cluster=~\"$cluster\"})), \"custom_label\", \"ping\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    }
   ]
  },
  {
   "title": "$cluster Broker connection latency",
   "type": "timeseries",
   "description": "broker connection latency trend.",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "label_replace(aio_broker_connect_latency_last_value_ms{cluster=\"$cluster\"},\"last_value\", \"$cluster: Broker connection last value\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{last_value}}"
    },
    {
     "expr": "label_replace(aio_broker_connect_latency_mu_ms{cluster=\"$cluster\"},\"mean_latency\", \"$cluster: Broker mean connection latency\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{mean_latency}}"
    },
    {
     "expr": "label_replace(aio_broker_connect_latency_sigma_ms{cluster=\"$cluster\"},\"std_deviation\", \"$cluster: Broker latency standard deviation\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{std_deviation}}"
    }
   ]
  },
  {
   "title": "$cluster MQTT Broker action latency overtime",
   "type": "timeseries",
   "description": "Average Broker latency across all its actions over time:\nConnection, Publish, Message Delivery, Subscribe, Unsubscribe",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace((avg by (cluster)(aio_broker_connect_latency_route_ms{cluster=~\"$cluster\"})), \"custom_label\", \"connect\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    },
    {
     "expr": "label_replace((avg by (cluster)(aio_broker_publish_latency_route_ms{cluster=~\"$cluster\"})), \"custom_label\", \"publish\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    },
    {
     "expr": "label_replace((avg by (cluster)(aio_broker_message_delivery_check_latency_last_value_ms{cluster=\"$cluster\"})),\"custom_label\", \"message delivery\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    },
    {
     "expr": "label_replace((avg by (cluster)(aio_broker_subscribe_latency_route_ms{cluster=~\"$cluster\"})), \"custom_label\", \"subscribe\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    },
    {
     "expr": "label_replace((avg by (cluster)(aio_broker_unsubscribe_latency_route_ms{cluster=~\"$cluster\"})), \"custom_label\", \"unsubscribe\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    },
    {
     "expr": "label_replace((avg by (cluster) (aio_broker_ping_latency_route_ms{cluster=~\"$cluster\"})), \"custom_label\", \"ping\", \"cluster\", \"$cluster\")",
     "legendFormat": "{{custom_label}}"
    }
   ]
  },
  {
   "title": "Storage Latency",
   "type": "table",
   "description": "storage account connectivity latency",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart's time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change \"group by column\" to a column in your table, such as \"Computer\". The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$ns",
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resources": [
       {
        "metricNamespace": "microsoft.storage/storageaccounts",
        "resourceGroup": "$rg",
        "resourceName": "$storage",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "100"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart's time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change \"group by column\" to a column in your table, such as \"Computer\". The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$ns",
      "metricName": "SuccessServerLatency",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resources": [
       {
        "metricNamespace": "Microsoft.Storage/storageAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$storage",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "100"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart's time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change \"group by column\" to a column in your table, such as \"Computer\". The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$ns",
      "metricName": "Ingress",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resources": [
       {
        "metricNamespace": "Microsoft.Storage/storageAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$storage",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "100"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart's time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change \"group by column\" to a column in your table, such as \"Computer\". The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$ns",
      "metricName": "Egress",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resources": [
       {
        "metricNamespace": "Microsoft.Storage/storageAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$storage",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "100"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    }
   ]
  },
  { "title": "Cloud", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Rest Client Duration / Count (Average Latency)",
   "type": "bargauge",
   "description": "Calculated Average route latency for rest client requests.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rest_client_request_duration_seconds_sum)by (verb) / sum(rest_client_request_duration_seconds_count) by (verb)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rest Client Hourly latency trends per route",
   "type": "timeseries",
   "description": "Client request trends scope to hourly intervals",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_request_duration_seconds_sum[$__rate_interval]))by (verb) / sum(rate(rest_client_request_duration_seconds_count[$__rate_interval])) by (verb)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95% of Rest Client Request",
   "type": "histogram",
   "description": "95% of Rest Client calls fall into this trend with some outliers",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rest_client_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}