{
 "title": "Service Performance",
 "description": "Dashboard to display service performance over CPU and memory usage.",
 "tags": [ "performance" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{phase!~\"terminating\"}"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", created_by_kind!=\"job\"},pod)"
    }
   },
   { "name": "datasource_uid", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage as % of Pod Memory Requests (All Pods)",
   "type": "timeseries",
   "description": "For any given pod, see memory usage expressed as a percentage of the total memory requested by that pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$usage/$requests", "type": "math" }
   ]
  },
  {
   "title": "CPU Usage as % of Pod CPU Requests (All Pods)",
   "type": "timeseries",
   "description": "For any given pod, see the CPU usage as a percentage of the CPU requested by the pod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$usage/$requests", "type": "math" }
   ]
  },
  {
   "title": "Memory Usage as Percent of Pod Memory Request",
   "type": "timeseries",
   "description": "for any given pod, see memory usage expressed as a percentage of the total memory requested by that pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$usage/$requests", "type": "math" }
   ]
  },
  {
   "title": "Cpu Usage as Percent of Pod Cpu Request",
   "type": "timeseries",
   "description": "for any given pod, see the cpu usage as a percentage of the cpu requested by the pod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$usage/$requests", "type": "math" }
   ]
  }
 ]
}