{
 "title": "Service Health",
 "tags": [
  "health",
  "shared"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource_uid", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "kube_node_status_condition" } },
   { "name": "namespace", "query": "azure-iot-operations" },
   { "name": "aio_dp_self_test_pipeline", "query": ".*self-test-pipeline.*" },
   { "name": "bf_latency_threshold_ms", "query": "500" },
   { "name": "aio_opc_latency_threshold_ms", "query": "5000" },
   { "name": "nodeThresholdRed", "query": "90" },
   { "name": "nodeThresholdYellow", "query": "80" },
   { "name": "opc_slo_sr_goal", "query": "99.999" },
   {
    "name": "opc_slo_publish_latency_ms_goal",
    "query": "5000"
   },
   {
    "name": "opc_slo_connect_latency_ms_goal",
    "query": "3000"
   },
   { "name": "orc_latency_threshold_ms", "query": "60000" },
   { "name": "aio_dp_error_threshold", "query": "20" },
   {
    "name": "aio_dp_nats_utilization_threshold",
    "query": "0.90"
   },
   { "name": "aio_dp_error_rate", "query": "0.05" },
   { "name": "aio_dp_latency_threshold_ms", "query": "5000" }
  ]
 },
 "panels": [
  { "title": "Azure Edge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Azure Edge Scenario Health",
   "type": "state-timeline",
   "description": "Checks if *_route_replication_correctness is available, if not - returns 404. The End-to-End health checks if any messages are lost and 404s if the messages are not available.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(min(\r\n    label_replace(label_replace((\r\n        min(aio_broker_publish_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/bf5237d2-7deb-4144-aa46-41e1c1629b30/aio-service-mq-publish\",\"\",\"\")\r\n        ,\"_\",\"Publish health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(aio_broker_subscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/b5d606dc-a841-4ec0-b7c5-4f1d37c4e877/aio-service-mq-subscribe\",\"\",\"\")\r\n        ,\"_\",\"Subscribe health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(aio_broker_unsubscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/d2a068a7-e4f0-40cc-bba9-29a263a38c58/aio-service-mq-unsubscribe\",\"\",\"\")\r\n        ,\"_\",\"Unsubscribe health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(\r\n            1 - min(\r\n                0 * sgn(\r\n                    sum(aio_broker_message_delivery_check_total_messages_lost{cluster=\"$cluster\", instance=~\"$namespace\"})\r\n                <= 0) or\r\n                1 * sgn(\r\n                    sum(aio_broker_message_delivery_check_total_messages_lost{cluster=\"$cluster\", instance=~\"$namespace\"})\r\n                > 0)) or vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/c84357d6-e4ef-4459-8348-6049269ace5c/aio-service-mq-payload-check\",\"\",\"\")\r\n        ,\"_\",\"End-to-end health\",\"\",\"\") or \r\n    vector(0) > 0 # Tail; not shown\r\n),\"_\",\"MQ Overall Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    },
    {
     "expr": "#label_replace(min(\r\n    label_replace(label_replace((\r\n        min(aio_broker_publish_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/bf5237d2-7deb-4144-aa46-41e1c1629b30/aio-service-mq-publish\",\"\",\"\")\r\n        ,\"_\",\"Publish health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(aio_broker_subscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/b5d606dc-a841-4ec0-b7c5-4f1d37c4e877/aio-service-mq-subscribe\",\"\",\"\")\r\n        ,\"_\",\"Subscribe health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(aio_broker_unsubscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/d2a068a7-e4f0-40cc-bba9-29a263a38c58/aio-service-mq-unsubscribe\",\"\",\"\")\r\n        ,\"_\",\"Unsubscribe health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(\r\n            1 - min(\r\n                0 * sgn(\r\n                    sum(aio_broker_message_delivery_check_total_messages_lost{cluster=\"$cluster\", instance=~\"$namespace\"})\r\n                <= 0) or\r\n                1 * sgn(\r\n                    sum(aio_broker_message_delivery_check_total_messages_lost{cluster=\"$cluster\", instance=~\"$namespace\"})\r\n                > 0)) or vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/c84357d6-e4ef-4459-8348-6049269ace5c/aio-service-mq-payload-check\",\"\",\"\")\r\n        ,\"_\",\"End-to-end health\",\"\",\"\") or \r\n    vector(0) > 0 # Tail; not shown\r\n#),\"_\",\"MQ Overall Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "Azure Edge Service Health",
   "type": "state-timeline",
   "description": "Authentication and Authorization failures check if the rate of authentication/authorization failures are less than 20 over 2 minute periods. Backpressure and QoS0 check if the ratio of the packets/messages is less than 5% over a 30 minute period. Broker overall health returns red if any of the others contain failures.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(min(\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(0)>0)\r\n        ,\"url\",\"/d/f41cdbe5-4075-4f05-aeb2-a34b5b46571c/aio-service-broker-connect\",\"\",\"\")\r\n        ,\"_\",\"Authentication failures\",\"\",\"\") or\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(0)>0)\r\n        ,\"url\",\"/d/c4c37068-3940-40ba-8c20-67b3ce4923e2/aio-service-broker-connect\",\"\",\"\")\r\n        ,\"_\",\"Authorization failures\",\"\",\"\") or        \r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(rate(aio_broker_backpressure_packets_rejected{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05) or\r\n            0 * sgn(\r\n                sum(rate(aio_broker_backpressure_packets_rejected{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            > 0.05)) or vector(0)>0)\r\n        ,\"url\",\"/d/eb3949b9-da3a-4b9e-8573-beb5507617a9/aio-service-broker-clusterperf\",\"\",\"\")\r\n        ,\"_\",\"Backpressure\",\"\",\"\") or\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(rate(aio_broker_qos0_messages_dropped{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05) or\r\n            0 * sgn(\r\n                sum(rate(aio_broker_qos0_messages_dropped{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            > 0.05)) or vector(0)>0)\r\n        ,\"url\",\"/d/eb3949b9-da3a-4b9e-8573-beb5507617a9/aio-service-broker-clusterperf\",\"\",\"\")\r\n        ,\"_\",\"Dropped QoS0 Msgs\",\"\",\"\") or\r\n    vector(404) # Tail; not shown\r\n),\"_\",\"Broker Overall Health\",\"\",\"\")\r\n",
     "legendFormat": "{{_}}"
    },
    {
     "expr": "#label_replace(min(\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(404))\r\n        ,\"url\",\"/d/f41cdbe5-4075-4f05-aeb2-a34b5b46571c/aio-service-broker-connect\",\"\",\"\")\r\n        ,\"_\",\"Authentication failures\",\"\",\"\") or\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(404))\r\n        ,\"url\",\"/d/f41cdbe5-4075-4f05-aeb2-a34b5b46571c/aio-service-broker-connect\",\"\",\"\")\r\n        ,\"_\",\"Authorization failures\",\"\",\"\") or        \r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(rate(aio_broker_backpressure_packets_rejected{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05) or\r\n            0 * sgn(\r\n                sum(rate(aio_broker_backpressure_packets_rejected{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            > 0.05)) or vector(404))\r\n        ,\"url\",\"/d/eb3949b9-da3a-4b9e-8573-beb5507617a9/aio-service-broker-clusterperf\",\"\",\"\")\r\n        ,\"_\",\"Backpressure\",\"\",\"\") or\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(rate(aio_broker_qos0_messages_dropped{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05) or\r\n            0 * sgn(\r\n                sum(rate(aio_broker_qos0_messages_dropped{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            > 0.05)) or vector(404))\r\n        ,\"url\",\"/d/eb3949b9-da3a-4b9e-8573-beb5507617a9/aio-service-broker-clusterperf\",\"\",\"\")\r\n        ,\"_\",\"Dropped QoS0 Msgs\",\"\",\"\") or\r\n    vector(0) > 0 # Tail; not shown\r\n#),\"_\",\"broker Overall Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    }
   ]
  },
  { "title": "AIO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "AIO Service Health",
   "type": "state-timeline",
   "description": "Checks the connectors, dataflows, and brokers, and returns red if errors are found, 404s if no messages, and green if there are messages and no errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(min(\r\n    0 * sgn(count (0 <\r\n        rate(aio_opc_mqtt_message_publishing_duration_count{\r\n            cluster=\"$cluster\",aio_opc_mqtt_publish_result!~\"(success|nomatchingsubscribers)\"\r\n        }[5m:1m])\r\n    )) or\r\n    0 * sgn(count (0 <\r\n        rate(aio_opc_session_connect_duration_count{\r\n            cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\",aio_opc_connect_result!=\"success\"\r\n        }[5m:1m])\r\n    )) or\r\n    sgn(0 < count( # Healthy activity\r\n        rate(aio_opc_mqtt_message_publishing_duration_count{\r\n            cluster=\"$cluster\",aio_opc_mqtt_publish_result=~\"(success|nomatchingsubscribers)\"\r\n        }[5m:1m]))\r\n    ) or\r\n    vector(0)>0 or vector(404)\r\n),\"_\",\"Connectors\",\"\",\"\")\r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(min(\r\n    0 * (count(0 < rate(aio_dataflow_errors{cluster='$cluster'}[5m:1m]))) or # Errors\r\n    1 * sgn(count(0 < rate(aio_dataflow_messages_sent{cluster='$cluster'}[5m:1m]))) or # Activity\r\n    vector(0) > 0 or vector(404)\r\n),\"_\",\"Dataflows\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(min(\r\n  # NEW Broker\r\n  label_replace(min(\r\n    0 * sgn(sum(rate(aio_broker_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) > 0) or\r\n    1 * sgn(sum(rate(aio_broker_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) ) or\r\n    vector(0)>0)\r\n    ,\"_\",\"Authentication failures\",\"\",\"\") or\r\n  label_replace(min(\r\n    0 * sgn(sum(rate(aio_broker_qos0_messages_dropped{pod_type=\"BE\",cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) > 0) or\r\n    1 * sgn(sum(rate(aio_broker_qos0_messages_dropped{pod_type=\"BE\",cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) ) or\r\n    vector(0)>0)\r\n    ,\"_\",\"Dropped QoS0 Msgs\",\"\",\"\") or\r\n  label_replace(\r\n    0 * max(kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"aio-broker-upgrade-status-job.*\", phase=~\"failed\"} == 1) or\r\n    1 * max(kube_job_status_succeeded{cluster=\"$cluster\", namespace=~\"$namespace\", job_name=~\"aio-broker-upgrade-status-job.*\"} == 1) or vector(404)\r\n    ,\"_\",\"Upgrade failures\",\"\",\"\") or  \r\n  vector(404) # Tail; not shown\r\n),\"_\",\"Broker\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AIO Scenario Health",
   "type": "state-timeline",
   "description": "Akri health is based on pod readiness percentage, Broker health is based on replication correctness and if there are lost messages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(min(\r\navg(label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n       kube_deployment_status_replicas_ready{cluster=\"$cluster\",namespace=~\".*\",deployment=~\"^aio-akri-agent.*\"} or\r\n       kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=~\".*\",daemonset=~\"^aio-akri-agent.*\"} or\r\n       kube_statefulset_status_replicas_ready{cluster=\"$cluster\",namespace=~\".*\",statefulset=~\"^aio-akri-agent.*\"}\r\n       ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n       ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n /\r\n  label_replace(label_join(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",namespace=~\".*\",daemonset=~\"^aio-akri-agent.*\"} or\r\n        kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=~\".*\",deployment=~\"^aio-akri-agent.*\"} or\r\n        kube_statefulset_status_replicas{cluster=\"$cluster\",namespace=~\".*\",statefulset=~\"^aio-akri-agent.*\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n) by (workload) >=0 \r\n) or vector(-1),\"_\",\"Akri Health\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(min(\r\n    label_replace(label_replace((\r\n        min(aio_broker_publish_route_replication_correctness{cluster=\"$cluster\"}) or vector(404))\r\n        ,\"url\",\"/d/THdxxxh4z/e4k-publish\",\"\",\"\")\r\n        ,\"_\",\"Publish health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(aio_broker_subscribe_route_replication_correctness{cluster=\"$cluster\"}) or vector(404))\r\n        ,\"url\",\"/d/d0318b5a-4afa-47e3-975f-6b1d2d783849/e4k-subscribe\",\"\",\"\")\r\n        ,\"_\",\"Subscribe health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(aio_broker_unsubscribe_route_replication_correctness{cluster=\"$cluster\"}) or vector(404))\r\n        ,\"url\",\"/d/d2a068a7-e4f0-40cc-bba9-29a263a38c58/aio-service-broker-unsubscribe\",\"\",\"\")\r\n        ,\"_\",\"Unsubscribe health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(\r\n            1 - min(\r\n                0 * sgn(\r\n                    sum(aio_broker_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n                <= 0) or\r\n                1 * sgn(\r\n                    sum(aio_broker_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n                > 0)) or vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/c84357d6-e4ef-4459-8348-6049269ace5c/aio-service-broker-payload-check\",\"\",\"\")\r\n        ,\"_\",\"End-to-end health\",\"\",\"\") or         \r\n    vector(0) > 0 # Tail; not shown\r\n),\"_\",\"Broker Health\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker overall messages delivered",
   "type": "stat",
   "description": "The average percentage of messages delivered over the given period of time",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - min(\r\n    0 * sgn(\r\n        sum(aio_broker_message_delivery_check_total_messages_lost{cluster=\"$cluster\", instance=~\"$namespace\"})\r\n    <= 0) or\r\n    1 * sgn(\r\n        sum(aio_broker_message_delivery_check_total_messages_lost{cluster=\"$cluster\", instance=~\"$namespace\"})\r\n    > 0)) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker subscribe health [%]",
   "type": "stat",
   "description": "Subscribe route's self test client is replicated correctly",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aio_broker_subscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AIO Broker Connected Sessions",
   "type": "timeseries",
   "description": "Number of sessions connected to the broker.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(_)(\r\n    label_replace(\r\n        aio_broker_connected_sessions{cluster='$cluster'}\r\n    ,'_','sessions','','')\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker unsubscribe health [%]",
   "type": "stat",
   "description": "Unsubscribe route's self test client is replicated correctly",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aio_broker_unsubscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker publish health [%]",
   "type": "stat",
   "description": "Publish route's self test client is replicated correctly",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aio_broker_publish_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker messages delivered success rate",
   "type": "timeseries",
   "description": "Visualization of the success rate of messages delivered, grouped by topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    (\r\n        sum(aio_broker_publish_route_replication_correctness{cluster=\"$cluster\"}) +\r\n        sum(aio_broker_subscribe_route_replication_correctness{cluster=\"$cluster\"}) +\r\n        sum(aio_broker_unsubscribe_route_replication_correctness{cluster=\"$cluster\"}) +\r\n        sum(\r\n            (1 - min(\r\n            0 * sgn(\r\n                sum(aio_broker_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n            <= 0) or\r\n            1 * sgn(\r\n                sum(aio_broker_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n            > 0)) or vector(0))\r\n            ) +\r\n    0) / (\r\n        count(aio_broker_publish_route_replication_correctness{cluster=\"$cluster\"}) +\r\n        count(aio_broker_subscribe_route_replication_correctness{cluster=\"$cluster\"}) +\r\n        count(aio_broker_unsubscribe_route_replication_correctness{cluster=\"$cluster\"}) +\r\n        count(\r\n            (1 - min(\r\n            0 * sgn(\r\n                sum(aio_broker_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n            <= 0) or\r\n            1 * sgn(\r\n                sum(aio_broker_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n            > 0)) or vector(0))\r\n            ) +\r\n    0)\r\n    ,\"_\",\".Overall\",\"\",\"\") * 100 or\r\nlabel_replace(\r\n    sum(aio_broker_publish_route_replication_correctness{cluster=\"$cluster\"}) / \r\n    count(aio_broker_publish_route_replication_correctness{cluster=\"$cluster\"})\r\n    ,\"_\",\"Publish\",\"\",\"\") * 100 or\r\nlabel_replace(\r\n    sum(aio_broker_subscribe_route_replication_correctness{cluster=\"$cluster\"}) / \r\n    count(aio_broker_subscribe_route_replication_correctness{cluster=\"$cluster\"})\r\n    ,\"_\",\"Subscribe\",\"\",\"\") * 100 or\r\nlabel_replace(\r\n    sum(aio_broker_unsubscribe_route_replication_correctness{cluster=\"$cluster\"}) / \r\n    count(aio_broker_unsubscribe_route_replication_correctness{cluster=\"$cluster\"})\r\n    ,\"_\",\"Unsubscribe\",\"\",\"\") * 100 or    \r\nlabel_replace(\r\n    sum(\r\n        (1 - min(\r\n            0 * sgn(\r\n                sum(aio_broker_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n            <= 0) or\r\n            1 * sgn(\r\n                sum(aio_broker_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n            > 0)) or vector(0))\r\n    ) / \r\n    count(\r\n        (1 - min(\r\n            0 * sgn(\r\n                sum(aio_broker_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n            <= 0) or\r\n            1 * sgn(\r\n                sum(aio_broker_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n            > 0)) or vector(0))    \r\n    )\r\n    ,\"_\",\"End-to-end\",\"\",\"\") * 100 or\r\n#label_replace(vector(1),\"_\",\"TODO: Success Rate\",\"\",\"\") or\r\nvector(0) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Inbound messages / s",
   "type": "timeseries",
   "description": "Broker inbound messages per second grouped by category",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (category) (rate(aio_broker_publishes_received{cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Dataflows Messages Sent by EndPointType and DataflowId [$cluster]",
   "type": "timeseries",
   "description": "Monitors the amount of dataflow messages being sent, bucketed based on endpoint type and dataflowID.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(_)(\r\n    label_replace(label_join(\r\n        increase(aio_dataflow_messages_sent{cluster='$cluster'}[5m:1m]),\r\n        '_',',','endpointtype','dataflowid'),'_','sent ($1) $2','_','^(.*),(.*)$')\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Outbound messages / s",
   "type": "timeseries",
   "description": "Broker outbound messages per second grouped by category",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (category) (rate(aio_broker_publishes_sent{cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  { "title": "mqtt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Mqtt Broker SLO",
   "type": "state-timeline",
   "description": "Checks for breaches of SLO. It will be red if auth failures > 20, auth denials > 20, rejected backpressure packets < 0.05, dropped QoS0 packets < 0.05.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "label_replace(min(\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(404))\r\n        ,\"url\",\"/d/f5a5c523-2cb6-42d8-b23f-06b0227fe40b/e4k-connect\",\"\",\"\")\r\n        ,\"_\",\"Authentication failures\",\"\",\"\") or\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_broker_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(404))\r\n        ,\"url\",\"/d/f5a5c523-2cb6-42d8-b23f-06b0227fe40b/e4k-connect\",\"\",\"\")\r\n        ,\"_\",\"Authorization failures\",\"\",\"\") or        \r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(rate(aio_broker_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05) or\r\n            0 * sgn(\r\n                sum(rate(aio_broker_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05)) or vector(404))\r\n        ,\"url\",\"/d/E19etH24z/e4k-cluster-perf\",\"\",\"\")\r\n        ,\"_\",\"Backpressure\",\"\",\"\") or\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(rate(aio_broker_qos0_messages_dropped{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05) or\r\n            0 * sgn(\r\n                sum(rate(aio_broker_qos0_messages_dropped{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_broker_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            > 0.05)) or vector(404))\r\n        ,\"url\",\"/d/eb3949b9-da3a-4b9e-8573-beb5507617a9/aio-service-broker-clusterperf\",\"\",\"\")\r\n        ,\"_\",\"Dropped QoS0 Msgs\",\"\",\"\") or\r\n    vector(0) > 0 # Tail; not shown\r\n),\"_\",\"Mqtt Broker SLO\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Kubernetes Node Health",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 48 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "# Node Health Status\r\n####################\r\n# RED (0) if no nodes ready without pressure\r\n# YELLOW (0.5) if at least one node not ready or with pressure\r\n# Green (1.0) otherwise\r\nlabel_replace(\r\n  sum(\r\n    max by (node) (kube_node_status_condition{cluster=\"$cluster\",condition=\"ready\",status=\"false\"} > 0) * 0 or\r\n    max by (node) (kube_node_status_condition{cluster=\"$cluster\",condition!=\"ready\",status=\"true\"} > 0) * 0.5 or\r\n    max by (node) (kube_node_status_condition{cluster=\"$cluster\",condition=\"ready\",status=\"true\"} > 0) * 1\r\n  ) / sum(kube_node_info{cluster=\"$cluster\"})\r\n  ,\"_\",\"Node Readiness\",\"\",\"\")\r\n#or label_replace(sum(kube_node_info),\"_\",\"Node Total Count\",\"\",\"\")\r\n#or label_replace(sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}),\"_\",\"Node Ready Count\",\"\",\"\")\r\n#or label_replace( sum(max by (node) (kube_node_status_condition{condition!=\"Ready\",status=\"true\"})),\"_\", \"Node Pressure Count\",\"\",\"\")\r\n#or label_replace(max by (node) (kube_node_status_condition{condition=\"Ready\",status=\"false\"}),\"_\",\"Node Ready Count\",\"\",\"\")\r\n#or label_replace(max by (node) (kube_node_status_condition{condition!=\"Ready\",status=\"true\"}),\"_\", \"Node Pressure Count\",\"\",\"\")\r\n#or label_replace(sum(sgn(\r\n#   max by (node) (kube_node_status_condition{condition=\"Ready\",status=\"false\"})\r\n# + max by (node) (kube_node_status_condition{condition!=\"Ready\",status=\"true\"})\r\n#  )),\"_\",\"Unhealthy Node Count\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Node CPU Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(_)(label_replace(vector(0)>0\r\n    or 0.0 * sgn(\r\n        100 - ((avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\"}[5m])) \r\n              + avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"iowait\"}[5m]))\r\n        ) * 100) > $nodeThresholdRed)\r\n    or 0.5 * sgn(\r\n        100 - ((avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\"}[5m])) \r\n              + avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"iowait\"}[5m]))\r\n        ) * 100) > $nodeThresholdYellow)\r\n    or 1.0 * sgn(sum by (instance)(node_cpu_seconds_total{cluster=\"$cluster\"} > 0))\r\n    or -1 * sgn(max by (instance) (label_replace(kube_node_info{cluster=\"$cluster\"},\"instance\",\"$1\",\"node\",\"(.*)\")))\r\n    ,\"_\",\"$1\",\"instance\",\"(.*)\"))\r\n# END inner query\r\n),\"_\",\"Node CPU\", \"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Node Memory Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(_)(label_replace(vector(0)>0\r\n    or 0.0 * sgn(\r\n        (100 * sum by (instance)(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - (node_memory_MemFree_bytes{cluster=\"$cluster\"} + node_memory_Buffers_bytes{cluster=\"$cluster\"} + node_memory_Cached_bytes{cluster=\"$cluster\"})) / sum by(instance) (node_memory_MemTotal_bytes{cluster=\"$cluster\"})) > $nodeThresholdRed)\r\n    or 0.5 * sgn(\r\n        (100 * sum by (instance)(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - (node_memory_MemFree_bytes{cluster=\"$cluster\"} + node_memory_Buffers_bytes{cluster=\"$cluster\"} + node_memory_Cached_bytes{cluster=\"$cluster\"})) / sum by(instance) (node_memory_MemTotal_bytes{cluster=\"$cluster\"})) > $nodeThresholdYellow)\r\n    or 1.0 * sgn(sum by (instance)(node_memory_MemTotal_bytes{cluster=\"$cluster\"} > 0))\r\n    or -1 * sgn(max by (instance) (label_replace(kube_node_info{cluster=\"$cluster\"},\"instance\",\"$1\",\"node\",\"(.*)\")))\r\n,\"_\",\"$1\",\"instance\",\"(.*)\"))\r\n# END inner query\r\n),\"_\",\"Node Memory\", \"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Disk Usage Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(node)(label_replace(vector(0)>0\r\n  or 0.0 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=\"$cluster\"}) > 10) > $nodeThresholdRed)\r\n  or 0.5 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=\"$cluster\"}) > 10) > $nodeThresholdYellow)\r\n  or 1.0 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=\"$cluster\"})))\r\n,\"node\",\"$1\",\"instance\",\"(.*)\"))\r\nor max by (node) (kube_node_info{cluster=\"$cluster\"}) * -1 # Baseline by node\r\n# END inner query\r\n),\"_\",\"Node Disk\", \"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Workload Health",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 52 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "## Workload Readiness health\r\n############################\r\nlabel_replace(min(\r\navg(label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_deployment_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=~\"$namespacem\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n  / label_replace(label_join(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_statefulset_status_replicas{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n) by (workload) >=0 \r\n) or vector(404),\"_\",\"AIO Workload Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Restart Health:\r\n############################\r\nlabel_replace(\r\n  sgn(sum_over_time(sum(rate(\r\n    kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[10m:1m]\r\n    )*60)[1h:]) > 5) * 0.0 # RED: Cumulative restarts over X(5) time greater than Y(1h)\r\n  or (max(rate(\r\n    kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m]\r\n    )*60*5) > 0) * 0.5 # YELLOW: restarts detected but below Red threshold\r\n  or sgn(max(\r\n    kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n    + 1 >= 0))\r\n  #or vector(1) # Healthy\r\n  ,\"_\",\"AIO Container Restarts\",\"\",\"\")\r\n## uncomment below to t-shoot this health metric\r\n# or label_replace(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=\"$cluster\"}[10m:1m])*60)[1h:]),\"_\",\"Total-restarts-over-time\",\"\",\"\")\r\n# or label_replace((max(rate(kube_pod_container_status_restarts_total{cluster=\"$cluster\"}[5m:1m])*60*5) without (__name__,uid,instance,job) > 0),\"_\",\"restart\",\"\",\"\") # Base query for counting restarts\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container CPU top-level health\r\n################################\r\nlabel_replace(\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m])\r\n    >= 0.60) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.0\r\nor\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m])\r\n    >= 0.40) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.5\r\nor\r\nmin( # Check to see if container is missing CPU Limits configuration\r\n    sgn(min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"cpu\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n    ) #by (namespace,container) # These are commented out for top-level\r\n,\"_\",\"AIO Container CPU\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Memory Health:\r\n###########################\r\nlabel_replace(\r\nmin( # Look for high memory utilization\r\n    0.0 * sgn((\r\n        max(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"memory\"}) by (namespace, container)\r\n    ) >= .95) or # show health state of 0 if container memory utilization >= 95%\r\n    0.5 * sgn((\r\n        max(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"memory\"}) by (namespace, container)\r\n    ) >= .80) or # show health state of 0.5 if container memory utilization >= 80%\r\n    vector(0)>0\r\n) #by (container) \r\nor\r\nmin( # Look for missing limits which we will show as 0 if missing\r\n    sgn(min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"memory\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n) #by (container) \r\n,\"_\",\"AIO Container Memory\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}