---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "basic-inference.fullname" . }}
  labels:
    {{- include "basic-inference.labels" . | nindent 4 }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "basic-inference.selectorLabels" . | nindent 4 }}
