---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chat-with-your-factory.fullname" . }}
  namespace: {{ include "chat-with-your-factory.namespace" . }}
  labels:
    {{- include "chat-with-your-factory.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
