---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aio-ssc-sa
  namespace: __AIO_OPERATIONS_NAMESPACE__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-federated-cred-sse
  namespace: cert-manager
