import sidebars from '../../sidebars';

describe('Sidebars configuration', () => {
  const docsSidebar = sidebars.docsSidebar as Array<Record<string, unknown>>;

  it('exports docsSidebar as an array', () => {
    expect(Array.isArray(docsSidebar)).toBe(true);
  });

  it('contains expected categories', () => {
    const labels = docsSidebar.map((item) => item.label);
    expect(labels).toContain('Getting Started');
    expect(labels).toContain('Contributing');
    expect(labels).toContain('Build & CI/CD');
    expect(labels).toContain('Observability');
  });

  it('uses autogenerated items', () => {
    const firstCategory = docsSidebar[0];
    const items = firstCategory.items as Array<Record<string, unknown>>;
    expect(items[0].type).toBe('autogenerated');
  });

  it('does not include learning categories', () => {
    const labels = docsSidebar.map((item) => item.label);
    expect(labels).not.toContain('Learning');
    expect(labels).not.toContain('Training Labs');
    expect(labels).not.toContain('Katas');
  });
});
