---
apiVersion: mqttbroker.iotoperations.azure.com/v1
kind: BrokerListener
metadata:
  name: default
  namespace: azure-iot-operations
spec:
  brokerRef: broker
  ports:
    - port: 1883
      protocol: Mqtt
    - port: 18883
      protocol: Mqtt
      tls:
        mode: Automatic
        certManagerCertificateSpec:
          issuerRef:
            group: cert-manager.io
            kind: ClusterIssuer
            name: azure-iot-operations-aio-certificate-issuer
          privateKey:
            algorithm: Ec256
            rotationPolicy: Always
  serviceName: aio-broker
  serviceType: loadBalancer
