---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: DataflowEndpoint
metadata:
  name: mqtt-l4-cert-auth
  namespace: azure-iot-operations
spec:
  endpointType: Mqtt
  mqttSettings:
    authentication:
      method: X509Certificate
      x509CertificateSettings:
        secretRef: client-secret
    clientIdPrefix: l4-client-cert-auth
    cloudEventAttributes: Propagate
    host: 10.1.1.4:18883
    keepAliveSeconds: 60
    maxInflightMessages: 100
    protocol: Mqtt
    qos: 1
    retain: Keep
    sessionExpirySeconds: 3600
    tls:
      mode: Enabled
      trustedCaCertificateConfigMapRef: tls-ca-configmap
