---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: Dataflow
metadata:
  name: event-grid-to-mqtt-df-{UNIQUE_POSTFIX}
  namespace: azure-iot-operations
spec:
  profileRef: df-profile
  mode: enabled
  operations:
    - operationType: source
      name: event-grid-source
      sourceSettings:
        endpointRef: {ENDPOINT_NAME}
        dataSources:
          - {DATA_SOURCE}
        serializationFormat: Json
    - operationType: destination
      name: mqtt-destination
      destinationSettings:
        endpointRef: default
        dataDestination: {DATA_DESTINATION}
