{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "model-orchestrator.serviceAccountName" . }}
  namespace: {{ include "model-orchestrator.namespace" . }}
  labels:
    {{- include "model-orchestrator.labels" . | nindent 4 }}
  annotations:
    {{- $workload := dict "aio-broker-auth/workload" (include "model-orchestrator.fullname" .) }}
    {{- merge (dict) (.Values.serviceAccount.annotations | default dict) $workload | toYaml | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
