---
# Resource Provider PowerShell Tests Workflow
#
# Purpose:
# This reusable workflow validates that PowerShell scripts for Azure resource provider
# registration and unregistration work correctly using Pester tests.
#
# Functionality:
# - Tests PowerShell scripts in the subscription management directory using Pester
# - Publishes test results as artifacts for troubleshooting failed tests
# - Displays test results directly in the GitHub interface
# - Can be conditionally called from PR validation or main branch workflows
#
# Parameters:
# - working-directory: Directory containing the resource provider scripts to test
# - test-results-output: Path to output PowerShell test results in NUnit format
#
# Output Variables:
# - None directly, but publishes test results as artifacts and to the GitHub interface
#
# Usage Examples:
# ```yaml
# # Basic usage in PR validation:
# pwsh-provider-tests:
#   name: PowerShell Provider Tests
#   needs: [mega-linter, changes]
#   if: needs.changes.outputs.changesInRpEnablementPwsh == 'true'
#   uses: ./.github/workflows/resource-provider-pwsh-tests.yml
#   with:
#     working-directory: 'src/azure-resource-providers'
#     test-results-output: 'PWSH-TEST-RESULTS.xml'
#
# # Usage in main workflow with custom path:
# pwsh-provider-tests-main:
#   name: PowerShell Resource Provider Tests (Main)
#   uses: ./.github/workflows/resource-provider-pwsh-tests.yml
#   with:
#     working-directory: 'custom/path/to/scripts'
# ```
#
# This workflow relies on the presence of Invoke-Pester.ps1 in the scripts directory
# to execute the tests. The tests are expected to be in the standard Pester format.

name: Resource Provider PowerShell Tests

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory containing the resource provider scripts'
        required: false
        type: string
        default: 'src/azure-resource-providers'
      test-results-output:
        description: 'Path to output PowerShell test results'
        required: false
        type: string
        default: 'PWSH-TEST-RESULTS.xml'

permissions:
  contents: read
jobs:
  # Job to run PowerShell script tests for the resource providers
  resource-provider-pwsh-test:
    name: PowerShell Resource Provider Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      # Run Pester tests for the resource provider scripts
      - name: Run Pester Tests
        shell: pwsh
        run: |
          ./scripts/Invoke-Pester.ps1 -Path ./${{ inputs.working-directory }} -OutputFile ${{ inputs.test-results-output }}
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Pester tests failed with exit code $LASTEXITCODE"
            exit $LASTEXITCODE
          }
        working-directory: ${{ github.workspace }}

      # Publish the Pester test results
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@2848b2cda0e5190984587ec6bb1f36730ca78d50
        with:
          name: pester-test-results
          path: ${{ inputs.test-results-output }}

          # Publish test results to the GitHub interface
          # - name: Publish to GitHub interface
          #   if: always()
          #   uses: EnricoMi/publish-unit-test-result-action@v2
          #   with:
          #     nunit_files: ${{ inputs.test-results-output }}
          #     check_name: "PowerShell Resource Provider Test Results"
