---
name: rust-tests

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate:
          - src/500-application/503-media-capture-service
          - src/500-application/507-ai-inference
          - src/500-application/507-ai-inference/ai-edge-inference-crate
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@d17fa930f29d14b5a8f7361cdbdf7bf1b722e982 # cargo-llvm-cov

      - name: Cache cargo build
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: ${{ matrix.crate }}

      - name: Generate Cobertura coverage
        working-directory: ${{ matrix.crate }}
        run: cargo llvm-cov --cobertura --output-path coverage.xml

      - name: Upload to Codecov
        if: success()
        uses: codecov/codecov-action@3f20e214133d0983f9a10f3d63b0faf9241a3daa # v6.0.0
        with:
          files: ${{ matrix.crate }}/coverage.xml
          use_oidc: true
          fail_ci_if_error: false
          verbose: true
          flags: rust
          name: rust-coverage-${{ matrix.crate }}
